function ContourPlots(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Jan-2022 01:42:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'LineStyle','--','Parent',axes1);
set(plot1(1),'DisplayName','Target pitch contour','LineWidth',6,...
    'Color',[0.800000011920929 0.800000011920929 0.800000011920929],...
    'LineStyle','-');


set(plot1(2),'DisplayName','Simulation 1',...
    'Color',[1 0.400000005960464 0.200000002980232]);
set(plot1(3),'DisplayName','Simulation 2',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(4),'DisplayName','Simulation 3',...
    'Color',[0.800000011920929 0.800000011920929 0]);
set(plot1(5),'DisplayName','Simulation 4',...
    'Color',[0.466666668653488 0.674509823322296 0.18823529779911]);
set(plot1(6),'DisplayName','Simulation 5',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot1(7),'DisplayName','Simulation 6','Color',[0 0 1]);
set(plot1(8),'DisplayName','Simulation 7',...
    'Color',[0.600000023841858 0 0.800000011920929]);


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.1 1.81]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[60 180]);
box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.754400342755927 0.151003262380372 0.131208150942183 0.250645077087933],...
    'FontSize',20,...
    'FontName','Times New Roman');

